name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-acme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install X11
        run: |
          sudo apt update
          sudo apt install libx11-dev libxt-dev libfontconfig1-dev

      - name: Configure
        run: ./configure acme

      - name: Build
        run: make

      - name: Install
        run: make prefix=./dist install

      - name: Find Files
        run: |
          find ./dist/bin -type f -name "acme"
          find ./dist/share/man/man1 -type f -name "acme.1"

  build-sam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install X11
        run: |
          sudo apt update
          sudo apt install libx11-dev libxt-dev libfontconfig1-dev

      - name: Configure
        run: ./configure sam

      - name: Build
        run: make

      - name: Install
        run: make prefix=./dist install

      - name: Find Files
        run: |
          find ./dist/bin -type f -name "sam"
          find ./dist/bin -type f -name "samterm"
          find ./dist/share/man/man1 -type f -name "sam.1"

  build-plan9tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install X11
        run: |
          sudo apt update
          sudo apt install libx11-dev libxt-dev libfontconfig1-dev

      - name: Configure
        run: ./configure tools

      - name: Build
        run: make

      - name: Install
        run: make prefix=./dist install

  build-nix:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build acme
        run: docker build --target acme .

      - name: build sam
        run: docker build --target sam .

      - name: build plan9tools
        run: docker build --target plan9tools .
